name: ExcavatorTools
version: 1.0.1
main: com.example.excavatortools.ExcavatorTools
api-version: '1.21'
commands:
  excavatortool:
    description: Quản lý ExcavatorTools
    usage: /<command> [give|reload] ...
    aliases: [xt]
permissions:
  excavatortool.admin:
    description: Cho phép dùng lệnh admin
    default: op
